name: 'Test'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  unit:
    name: 'unit'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v3'

      - uses: 'actions/setup-node@v2'
        with:
          node-version: '16.x'

      - name: 'npm test'
        run: 'npm run test'

      # example only
      - name: 'Custom Data'
        run: |
          echo "test_coverage=22" > $GITHUB_JOB_OUTPUT
          echo "binary_size_mb=110" > $GITHUB_JOB_OUTPUT
