on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Threadfix connector
        uses: AlexDeMichieli/insecure-test-app@master
        with: # Set the secret as an input
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TFIX_API_KEY: ${{secrets.TFIX_API_KEY}}
          TFIX_INSTANCE_URL: ${{secrets.TFIX_INSTANCE_URL}}
          TFIX_APP_ID: ${{secrets.TFIX_APP_ID}}


