on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Threadfix connector
        uses: AlexDeMichieli/insecure-test-app@v1

